// <auto-generated />
using System;
using BoardGameReviews.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoardGameReviews.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505143213_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BoardGameReviews.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeGroup")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Popularity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeGroup = "12+",
                            Description = "Games focused on planning and tactics",
                            Difficulty = 2,
                            Name = "Strategy",
                            Popularity = 95
                        },
                        new
                        {
                            Id = 2,
                            AgeGroup = "14+",
                            Description = "Games with exploration and narrative",
                            Difficulty = 1,
                            Name = "Adventure",
                            Popularity = 85
                        },
                        new
                        {
                            Id = 3,
                            AgeGroup = "13+",
                            Description = "Games set in magical worlds",
                            Difficulty = 2,
                            Name = "Fantasy",
                            Popularity = 90
                        });
                });

            modelBuilder.Entity("BoardGameReviews.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDateTime = new DateTime(2026, 6, 5, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 1,
                            Location = "Board Game Cafe - Zagreb",
                            Name = "Catan Tournament",
                            StartDateTime = new DateTime(2026, 6, 5, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            EndDateTime = new DateTime(2026, 6, 12, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 2,
                            Location = "Card Shop Downtown",
                            Name = "Magic Draft Night",
                            StartDateTime = new DateTime(2026, 6, 12, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            EndDateTime = new DateTime(2026, 6, 20, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 3,
                            Location = "Gaming Studio - Novi Sad",
                            Name = "Warhammer 40K Campaign",
                            StartDateTime = new DateTime(2026, 6, 20, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BoardGameReviews.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("GameTypeId")
                        .HasColumnType("int");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("int");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GameTypeId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Trade, build, and settle the island of Catan.",
                            Difficulty = 1,
                            GameTypeId = 1,
                            MaxPlayers = 4,
                            MinPlayers = 2,
                            Name = "Catan",
                            PublisherId = 1,
                            YearPublished = 1995
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Collectible card game of strategy.",
                            Difficulty = 2,
                            GameTypeId = 2,
                            MaxPlayers = 2,
                            MinPlayers = 2,
                            Name = "Magic: The Gathering",
                            PublisherId = 2,
                            YearPublished = 1993
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Miniatures game in a sci-fi universe.",
                            Difficulty = 2,
                            GameTypeId = 1,
                            MaxPlayers = 4,
                            MinPlayers = 2,
                            Name = "Warhammer 40K",
                            PublisherId = 3,
                            YearPublished = 1987
                        });
                });

            modelBuilder.Entity("BoardGameReviews.Models.GameType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("GameTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Traditional board game",
                            Name = "Board Game"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Game played with cards",
                            Name = "Card Game"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Game using dice",
                            Name = "Dice Game"
                        });
                });

            modelBuilder.Entity("BoardGameReviews.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Germany",
                            Name = "Catan Studio"
                        },
                        new
                        {
                            Id = 2,
                            Country = "France",
                            Name = "Asmodee"
                        },
                        new
                        {
                            Id = 3,
                            Country = "UK",
                            Name = "Games Workshop"
                        });
                });

            modelBuilder.Entity("BoardGameReviews.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRecommended")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Catan is fantastic for game nights.",
                            CreatedAt = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 1,
                            IsRecommended = true,
                            Rating = 5,
                            Title = "Excellent Classic Game",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Magic: The Gathering is deep and strategic.",
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 2,
                            IsRecommended = true,
                            Rating = 4,
                            Title = "Complex but Rewarding",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Warhammer 40K is impressive but expensive.",
                            CreatedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameId = 3,
                            IsRecommended = false,
                            Rating = 3,
                            Title = "Not for Everyone",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("BoardGameReviews.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 28,
                            Country = "Croatia",
                            Email = "master@boardgames.com",
                            HashedPassword = "hashed_password_1",
                            Username = "BoardGameMaster"
                        },
                        new
                        {
                            Id = 2,
                            Age = 35,
                            Country = "Serbia",
                            Email = "strategy@boardgames.com",
                            HashedPassword = "hashed_password_2",
                            Username = "StrategyKing"
                        },
                        new
                        {
                            Id = 3,
                            Age = 23,
                            Country = "Bosnia",
                            Email = "casual@boardgames.com",
                            HashedPassword = "hashed_password_3",
                            Username = "CasualGamer"
                        });
                });

            modelBuilder.Entity("BoardGameReviews.Models.Event", b =>
                {
                    b.HasOne("BoardGameReviews.Models.Game", "Game")
                        .WithMany("Events")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("BoardGameReviews.Models.Game", b =>
                {
                    b.HasOne("BoardGameReviews.Models.Category", "Category")
                        .WithMany("Games")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BoardGameReviews.Models.GameType", "GameType")
                        .WithMany("Games")
                        .HasForeignKey("GameTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BoardGameReviews.Models.Publisher", "Publisher")
                        .WithMany("Games")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("GameType");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("BoardGameReviews.Models.Review", b =>
                {
                    b.HasOne("BoardGameReviews.Models.Game", "Game")
                        .WithMany("Reviews")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BoardGameReviews.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BoardGameReviews.Models.Category", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("BoardGameReviews.Models.Game", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BoardGameReviews.Models.GameType", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("BoardGameReviews.Models.Publisher", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("BoardGameReviews.Models.User", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
